# ***Recap of Numpy***

In [2]:
import numpy as np


### **Numpy is created using np.array() passing object**

In [8]:
np.array([1,2,3])

array([1, 2, 3])

## **Creating One Dimensional array**

In [9]:
a=np.array([i for i in np.arange(1,10) if i%2==0 ])
print(a)

[2 4 6 8]


**Creating Two Dimensional array**

In [16]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


**Creating Two Dimensional array**

In [18]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
print(type(c))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


**Dtype**

In [19]:
d=np.array([2,4,6,8],dtype=float)
print(d)
print(type(d))

[2. 4. 6. 8.]
<class 'numpy.ndarray'>


**np.arange(start,stop,steps)**

In [27]:
arange=np.arange(1,12,2)
print(arange)

[ 1  3  5  7  9 11]


**np.rehsape(row,column)**

In [32]:
arange=np.arange(1,12,2).reshape(3,2)
print(arange)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


np.ones(shape)===>3,4

In [35]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.zeros(shape)===>3,4

In [36]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**# np.random(shape)===>(4,4)**

In [41]:
gen=np.random.random((3,4))
gen.reshape(6,2)

array([[0.71060127, 0.14184301],
       [0.97324171, 0.38191638],
       [0.26207908, 0.87571943],
       [0.20979399, 0.56203588],
       [0.04674064, 0.57834066],
       [0.89947473, 0.05333921]])

**np.linspace(-10,10,10)**

In [42]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

**Identity array===>np.identity(shappe)**

In [47]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

##  **Attributes of Arrays**

In [3]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [4]:
print(type(a1))
print(type(a2))
print(type(a3))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**ndim**

In [58]:
a1.ndim


1

In [59]:
a2.ndim


2

In [60]:
a3.ndim

3

**SHAPE**

In [62]:
a1.shape

(10,)

In [65]:
a2.shape

(3, 4)

In [63]:
a3.shape

(2, 2, 2)

**Attribute  SIZE**

In [5]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


**Attribute itemsize**

In [7]:
a1.itemsize
a2.itemsize
a3.itemsize

8

**Attribute dtype**

In [10]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


**Changing Datatype - astype**

In [11]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [16]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
# b3=np.arange(12).reshape(3,4)

b2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Scalar Operation**

In [20]:
# arthimatic
b1**2
# when an array is been operated by single unit

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational
b1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

**VECTOR OPERATIONS**

In [24]:
# WHEN TWO NP.ARRAY ARE OPERATED TOGETHER ARE CALLED VECTOR OPERATION
b2 * b1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [25]:
b1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [26]:
b1+b2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])