# ***Recap of Numpy***

In [2]:
import numpy as np


**Numpy is created using np.array() passing object**

In [8]:
np.array([1,2,3])

array([1, 2, 3])

**Creating One Dimensional array**

In [9]:
a=np.array([i for i in np.arange(1,10) if i%2==0 ])
print(a)

[2 4 6 8]


**Creating Two Dimensional array**

In [16]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


**Creating Two Dimensional array**

In [18]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
print(type(c))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


**Dtype**

In [19]:
d=np.array([2,4,6,8],dtype=float)
print(d)
print(type(d))

[2. 4. 6. 8.]
<class 'numpy.ndarray'>


**np.arange(start,stop,steps)**

In [27]:
arange=np.arange(1,12,2)
print(arange)

[ 1  3  5  7  9 11]


**np.rehsape(row,column)**

In [32]:
arange=np.arange(1,12,2).reshape(3,2)
print(arange)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


**np.ones(shape)===>3,4**

In [35]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**np.zeros(shape)===>3,4**

In [36]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**# np.random(shape)===>(4,4)**

In [41]:
gen=np.random.random((3,4))
gen.reshape(6,2)

array([[0.71060127, 0.14184301],
       [0.97324171, 0.38191638],
       [0.26207908, 0.87571943],
       [0.20979399, 0.56203588],
       [0.04674064, 0.57834066],
       [0.89947473, 0.05333921]])

**np.linspace(-10,10,10)**

In [42]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

**Identity array===>np.identity(shappe)**

In [47]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

***Attributes of Arrays***

In [91]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [4]:
print(type(a1))
print(type(a2))
print(type(a3))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**ndim**

In [58]:
a1.ndim


1

In [59]:
a2.ndim


2

In [60]:
a3.ndim

3

**SHAPE**

In [62]:
a1.shape

(10,)

In [65]:
a2.shape

(3, 4)

In [63]:
a3.shape

(2, 2, 2)

**Attribute  SIZE**

In [5]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


**Attribute itemsize**

In [7]:
a1.itemsize
a2.itemsize
a3.itemsize

8

**Attribute dtype**

In [10]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


**Changing Datatype - astype**

In [11]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [16]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
# b3=np.arange(12).reshape(3,4)

b2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Scalar Operation**

In [20]:
# arthimatic
b1**2
# when an array is been operated by single unit

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational
b1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

**VECTOR OPERATIONS**

In [24]:
# WHEN TWO NP.ARRAY ARE OPERATED TOGETHER ARE CALLED VECTOR OPERATION
b2 * b1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [25]:
b1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [26]:
b1+b2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**NumPy Array Functions**

In [9]:
# Exercise 1
x=np.ones((2,3))
print(x.shape)
print(x.ndim)
print(x.dtype)

(2, 3)
2
float64


In [10]:
# Exercise 2
np.arange(10,28,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26])

In [28]:
# Exercise
gen=np.random.random((20,5))
print('Mean',gen.mean())
gen > 0.8

Mean 0.45714556080087126


array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False,  True],
       [ True, False,  True, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

**Functions of Numpy**

In [32]:
c1=np.random.random((3,3))
c1=np.round(c1*100)
c1

array([[38., 28., 57.],
       [57., 10., 30.],
       [19., 68., 27.]])

In [46]:
# Max/Min/Sum/Prod 
print('Min: ',np.min(c1))
print('Sum: ',np.sum(c1))
print('Product: ',np.prod(c1))
# what if we need max/min of special row or column axis=0--->col axis=1--->row
# Row
np.max(c1,axis=1)
# Column
np.min(c1,axis=0)


Min:  10.0
Sum:  334.0
Product:  36177526627200.0


array([19., 10., 27.])

In [50]:
# Mean/Median/Std/Var 
print('Mean: ',np.mean(c1,axis=0))
print('Median: ',np.median(c1,axis=1))
print('Standard diviation: ',np.std(c1,axis=1))
print('Variance: ',np.var(c1,axis=1))

Mean:  [38.         35.33333333 38.        ]
Median:  [38. 30. 27.]
Standard diviation:  [12.0277457  19.25847577 21.46314671]
Variance:  [144.66666667 370.88888889 460.66666667]


**Trignometry Funions**

In [54]:
x = np.array([0, np.pi/2, np.pi])
x
print(np.sin(x))   # sine
print(np.cos(x))   # cosine
print(np.tan(x))   # tangent

# Inverse trigonometric functions
print(np.arcsin([0, 1]))  # inverse sine
print(np.arccos([1, 0]))  # inverse cosine
print(np.arctan([0, 1]))  # inverse tangent

# Hypotenuse
print(np.hypot(3, 4))     # returns sqrt(3^2 + 4^2) = 5

# Conversion between degrees and radians
print(np.deg2rad([0, 180]))  # degrees → radians
print(np.rad2deg([0, np.pi]))# radians → degrees

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0.         1.57079633]
[0.         1.57079633]
[0.         0.78539816]
5.0
[0.         3.14159265]
[  0. 180.]


**Dot Product**

In [58]:
b2=np.arange(12).reshape(3,4)
b3=np.arange(12,24).reshape(4,3)
np.dot(b2,b3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

**Log and Exponents**

In [60]:
print('Log: ',np.log(b2))
print('Exponents: ',np.exp(b2))

Log:  [[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
Exponents:  [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


C:\Users\etopi.DESKTOP-51VUFOC\AppData\Local\Temp\ipykernel_4920\3956721915.py:1: RuntimeWarning: divide by zero encountered in log
  print('Log: ',np.log(b2))


In [68]:
# Round/floor/ceil
np.round(np.random.random((2,3))*100)
np.ceil(np.round(np.random.random((2,3))*100))
np.floor(np.round(np.random.random((2,3))*100))


array([[89., 57., 98.],
       [87., 18., 13.]])

**Indexing and Slicing**

In [69]:
d1=np.arange(10)
d2=np.arange(12).reshape(3,4)
d3=np.arange(8).reshape(2,2,2)

In [70]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
d3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
# Index using list remain same with Numpy
d1[9]

np.int64(9)

In [79]:
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
d2[2,3]

np.int64(11)

In [86]:
# In numpy for finding index we can first indicate row and than finding element in column
d2[1,2]
d2[1,0]


np.int64(4)

In [ ]:
a3 #Tensors

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
a3[1,0,1]

np.int64(5)

In [94]:
a3[0,0,0]

np.int64(0)

In [95]:
a3[1,1,0]

np.int64(6)

***Slicing***

In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a1[2:5]

array([2, 3, 4])

In [104]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [112]:
a2[:]

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [102]:
a2[:,2]

array([ 2.,  6., 10.])

In [110]:
a2[1,1:,1,2]

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed