## Numpy array and Basics
Learn about numpy with nxtanalyst


In [2]:
import numpy as np

## Creating array From list

In [2]:
arry_1d=np.array([1,2,3,4,5])
print(f'Id Arrary=={arry_1d}')
arry_2d=np.array([[1,2,3],[4,5,6]])
print('2D array is: ',arry_2d)

Id Arrary==[1 2 3 4 5]
2D array is:  [[1 2 3]
 [4 5 6]]


## Numpy array Vs List


In [4]:
py_list=[1,2,3,4]
print('Python list multiplication',py_list*3)

np_array=np.array([1,2,3,4])
print('Python Array multiplication',np_array*2)
import time
start=time.time()
my_lis=[i*2 for i in range(1000000)]
print('Python list multiplication',time.time()-start)

start=time.time()
np_arrays=np.arange(1000000)*2
print('Python list multiplication',time.time()-start)




Python list multiplication [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Python Array multiplication [2 4 6 8]
Python list multiplication 0.11571145057678223
Python list multiplication 0.004536628723144531


## Creating Array From Scratch

In [ ]:
zeros=np.zeros((3,4))
print('Zeros Arayys: \n',zeros)

ones=np.ones((2,3))
print('Ones Arayys: \n',ones)

full=np.full(((2,2)),7)
print('Full Arayys: \n',full)
random=np.random.random((2,3))
print('Random Arayys: \n',random)

sequence=np.arange(0,10,2)
print('Sequence Arayys: \n',sequence)


Zeros Arayys: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Arayys: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Arayys: 
 [[7 7]
 [7 7]]
Random Arayys: 
 [[0.83357421 0.40265238 0.76380828]
 [0.48783555 0.12336353 0.644406  ]]
Sequence Arayys: 
 [0 2 4 6 8]


## np.linspace(-10,10,10)

In [3]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Identity array===>np.identity(shappe)

In [10]:
a=np.identity(4)
print(a)
type(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy.ndarray

## Vector, Matrix and Tenser

In [18]:
vector=np.array([1,2,3])
print('Vector',vector)

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print('Matrix:', matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print('Tensor:', tensor)

Vector [1 2 3]
Matrix: [[1 2 3 4]
 [5 6 7 8]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [21]:
arr=np.array([[1,2,3],
             [4,5,6]])

print('Shape: ',arr.shape)
print('Dimension: ',arr.ndim)
print('Size: ',arr.size)
print('Dtype: ',arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


### Array Reshaping

In [28]:
arr=np.arange(12)
print('Orignal array',arr)

reshaped=arr.reshape((3,4))
print('Reshaped array',reshaped)

flatend=reshaped.flatten()
print('Flattend array',flatend)

# ravel (Returns View, instead of copy)
ravel=reshaped.ravel()
print('Ravel array',ravel)

# Transpose
transpose=reshaped.T
print('Transpose array',transpose)


Orignal array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
