## Numpy array and Basics
Learn about numpy with nxtanalyst


In [2]:
import numpy as np

## Creating array From list

In [2]:
arry_1d=np.array([1,2,3,4,5])
print(f'Id Arrary=={arry_1d}')
arry_2d=np.array([[1,2,3],[4,5,6]])
print('2D array is: ',arry_2d)

Id Arrary==[1 2 3 4 5]
2D array is:  [[1 2 3]
 [4 5 6]]


## Numpy array Vs List


In [4]:
py_list=[1,2,3,4]
print('Python list multiplication',py_list*3)

np_array=np.array([1,2,3,4])
print('Python Array multiplication',np_array*2)
import time
start=time.time()
my_lis=[i*2 for i in range(1000000)]
print('Python list multiplication',time.time()-start)

start=time.time()
np_arrays=np.arange(1000000)*2
print('Python list multiplication',time.time()-start)




Python list multiplication [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Python Array multiplication [2 4 6 8]
Python list multiplication 0.11571145057678223
Python list multiplication 0.004536628723144531


## Creating Array From Scratch

In [15]:
zeros=np.zeros((3,4))
print('Zeros Arayys: \n',zeros)

ones=np.ones((2,3))
print('Ones Arayys: \n',ones)

full=np.full(((2,2)),7)
print('Full Arayys: \n',full)
random=np.random.random((2,3))
print('Random Arayys: \n',random)

sequence=np.arange(0,10,2)
print('Sequence Arayys: \n',sequence)


Zeros Arayys: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Arayys: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Arayys: 
 [[7 7]
 [7 7]]
Random Arayys: 
 [[0.83357421 0.40265238 0.76380828]
 [0.48783555 0.12336353 0.644406  ]]
Sequence Arayys: 
 [0 2 4 6 8]
